# Generated by Django 5.2.15 on 2026-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Merchant's final/last selling price — internal accounting only", max_digits=10, null=True),
        ),
    ]
