# Generated by Django 5.2.15 on 2026-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fb_post_id',
            field=models.CharField(blank=True, help_text='Facebook post ID this product is advertised in', max_length=120, null=True),
        ),
    ]
