# Generated by Django 5.2.16 on 2026-07-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_fb_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_hero_images/'),
        ),
    ]
