export const categories = [
  { id: 'electronics', name: 'Electronics', icon: '💻', image: 'https://picsum.photos/seed/electronics99/600/400', count: 48 },
  { id: 'clothing', name: 'Clothing', icon: '👕', image: 'https://picsum.photos/seed/fashion88/600/400', count: 125 },
  { id: 'home', name: 'Home & Garden', icon: '🏠', image: 'https://picsum.photos/seed/homegoods77/600/400', count: 64 },
  { id: 'sports', name: 'Sports', icon: '⚽', image: 'https://picsum.photos/seed/sports66/600/400', count: 39 },
  { id: 'beauty', name: 'Beauty', icon: '✨', image: 'https://picsum.photos/seed/beauty55/600/400', count: 57 },
]

export const products = [
  // Electronics
  {
    id: '1',
    name: 'Wireless Noise-Cancelling Headphones Pro',
    price: 279.99,
    originalPrice: 399.99,
    category: 'electronics',
    rating: 4.8,
    reviews: 2847,
    stock: 15,
    badge: 'Sale',
    description: 'Industry-leading noise canceling powered by two processors and eight microphones. Enjoy 30-hour battery life with quick charging capability. Multi-point connection lets you seamlessly switch between two devices.',
    features: ['30hr battery life', 'Active Noise Cancellation', 'Multipoint Bluetooth 5.2', 'Touch sensor controls', 'Speak-to-chat technology', 'Foldable design'],
    images: [
      'https://picsum.photos/seed/headphones1a/600/600',
      'https://picsum.photos/seed/headphones1b/600/600',
      'https://picsum.photos/seed/headphones1c/600/600',
      'https://picsum.photos/seed/headphones1d/600/600',
    ],
    variants: { colors: ['Midnight Black', 'Platinum Silver', 'Midnight Blue'] },
    tags: ['headphones', 'audio', 'wireless', 'anc'],
  },
  {
    id: '2',
    name: 'Ultra Slim 4K OLED Monitor 27"',
    price: 649.99,
    originalPrice: null,
    category: 'electronics',
    rating: 4.6,
    reviews: 1203,
    stock: 8,
    badge: 'New',
    description: 'Experience stunning visuals with our 27-inch 4K OLED display. With 1ms response time and 144Hz refresh rate, this monitor is perfect for both professional work and gaming.',
    features: ['4K OLED panel', '144Hz refresh rate', '1ms response time', 'USB-C 90W PD', 'Height adjustable stand', 'VESA compatible'],
    images: [
      'https://picsum.photos/seed/monitor2a/600/600',
      'https://picsum.photos/seed/monitor2b/600/600',
      'https://picsum.photos/seed/monitor2c/600/600',
    ],
    variants: { colors: ['Space Gray', 'Matte Black'] },
    tags: ['monitor', 'display', '4k', 'oled'],
  },
  {
    id: '3',
    name: 'Compact Mirrorless Camera Kit',
    price: 1299.99,
    originalPrice: 1499.99,
    category: 'electronics',
    rating: 4.9,
    reviews: 876,
    stock: 5,
    badge: 'Hot',
    description: 'Capture every moment in stunning detail with this compact mirrorless camera. Featuring a 24MP sensor, 4K video recording, and advanced autofocus system with eye-tracking.',
    features: ['24MP APS-C sensor', '4K 60fps video', 'In-body stabilization', 'Eye-tracking AF', 'Weather sealed', '400 shots per charge'],
    images: [
      'https://picsum.photos/seed/camera3a/600/600',
      'https://picsum.photos/seed/camera3b/600/600',
      'https://picsum.photos/seed/camera3c/600/600',
    ],
    variants: { colors: ['Black', 'Silver'] },
    tags: ['camera', 'photography', 'mirrorless', '4k'],
  },
  {
    id: '4',
    name: 'Smart Watch Series X',
    price: 349.99,
    originalPrice: 429.99,
    category: 'electronics',
    rating: 4.5,
    reviews: 3421,
    stock: 22,
    badge: 'Sale',
    description: 'Stay connected and track your health with this advanced smartwatch. Featuring an always-on display, comprehensive health monitoring, and 18-hour battery life.',
    features: ['Always-on Retina display', 'Blood oxygen monitoring', 'ECG app', '18hr battery', 'GPS + Cellular', 'Swimproof (50m)'],
    images: [
      'https://picsum.photos/seed/watch4a/600/600',
      'https://picsum.photos/seed/watch4b/600/600',
      'https://picsum.photos/seed/watch4c/600/600',
    ],
    variants: {
      colors: ['Midnight', 'Starlight', 'Product Red', 'Blue'],
      sizes: ['41mm', '45mm'],
    },
    tags: ['smartwatch', 'fitness', 'health', 'wearable'],
  },
  // Clothing
  {
    id: '5',
    name: 'Premium Cotton Relaxed Tee',
    price: 34.99,
    originalPrice: null,
    category: 'clothing',
    rating: 4.4,
    reviews: 567,
    stock: 50,
    badge: null,
    description: 'Crafted from 100% organic Pima cotton, this relaxed-fit t-shirt offers unmatched softness and durability. Pre-shrunk and GOTS certified.',
    features: ['100% organic Pima cotton', 'Pre-shrunk', 'GOTS certified', 'Reinforced seams', 'Tag-free neck label', 'Machine washable'],
    images: [
      'https://picsum.photos/seed/tshirt5a/600/600',
      'https://picsum.photos/seed/tshirt5b/600/600',
      'https://picsum.photos/seed/tshirt5c/600/600',
    ],
    variants: {
      colors: ['White', 'Black', 'Navy', 'Sage', 'Clay'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    },
    tags: ['tshirt', 'basics', 'organic', 'cotton'],
  },
  {
    id: '6',
    name: 'Slim Fit Stretch Chinos',
    price: 79.99,
    originalPrice: 99.99,
    category: 'clothing',
    rating: 4.3,
    reviews: 892,
    stock: 35,
    badge: 'Sale',
    description: 'These slim-fit chinos combine style and comfort with a 4-way stretch fabric. Perfect for the office or weekend, they keep their shape all day long.',
    features: ['4-way stretch fabric', 'Slim fit', 'Wrinkle resistant', 'UPF 30+ protection', 'Hidden waistband adjustment', 'Machine washable'],
    images: [
      'https://picsum.photos/seed/chinos6a/600/600',
      'https://picsum.photos/seed/chinos6b/600/600',
      'https://picsum.photos/seed/chinos6c/600/600',
    ],
    variants: {
      colors: ['Khaki', 'Navy', 'Olive', 'Charcoal', 'Stone'],
      sizes: ['28', '30', '32', '34', '36', '38'],
    },
    tags: ['pants', 'chinos', 'slim', 'stretch'],
  },
  {
    id: '7',
    name: 'Minimalist Leather Sneakers',
    price: 129.99,
    originalPrice: null,
    category: 'clothing',
    rating: 4.7,
    reviews: 1456,
    stock: 18,
    badge: 'New',
    description: 'Clean lines meet premium leather in these versatile sneakers. Hand-crafted from full-grain leather with a cushioned memory foam insole for all-day comfort.',
    features: ['Full-grain leather upper', 'Memory foam insole', 'Rubber cupsole', 'Antique brass eyelets', 'Leather lining', 'Unisex sizing'],
    images: [
      'https://picsum.photos/seed/sneakers7a/600/600',
      'https://picsum.photos/seed/sneakers7b/600/600',
      'https://picsum.photos/seed/sneakers7c/600/600',
    ],
    variants: {
      colors: ['White/White', 'White/Gum', 'Black/Black', 'Tan/Brown'],
      sizes: ['6', '7', '8', '9', '10', '11', '12'],
    },
    tags: ['sneakers', 'leather', 'shoes', 'minimalist'],
  },
  {
    id: '8',
    name: 'Oversized Knit Cardigan',
    price: 89.99,
    originalPrice: 119.99,
    category: 'clothing',
    rating: 4.6,
    reviews: 734,
    stock: 28,
    badge: 'Sale',
    description: 'Wrap yourself in luxury with this oversized chunky knit cardigan. Made from a soft wool blend, it features deep pockets and an open-front design.',
    features: ['60% wool, 40% acrylic blend', 'Oversized silhouette', 'Deep front pockets', 'Ribbed cuffs and hem', 'Open-front design', 'Hand wash recommended'],
    images: [
      'https://picsum.photos/seed/cardigan8a/600/600',
      'https://picsum.photos/seed/cardigan8b/600/600',
      'https://picsum.photos/seed/cardigan8c/600/600',
    ],
    variants: {
      colors: ['Cream', 'Camel', 'Dusty Rose', 'Sage', 'Charcoal'],
      sizes: ['XS/S', 'M/L', 'XL/XXL'],
    },
    tags: ['cardigan', 'knitwear', 'cozy', 'wool'],
  },
  // Home & Garden
  {
    id: '9',
    name: 'Minimalist Desk Lamp with Wireless Charger',
    price: 89.99,
    originalPrice: null,
    category: 'home',
    rating: 4.5,
    reviews: 423,
    stock: 31,
    badge: 'New',
    description: 'This elegant desk lamp features a built-in 15W wireless charger, adjustable color temperature, and stepless dimming via a touch panel. USB-A port for additional charging.',
    features: ['15W wireless Qi charging', '3 color temperatures', 'Stepless dimming', 'USB-A 5W port', 'Memory function', 'Flexible arm'],
    images: [
      'https://picsum.photos/seed/lamp9a/600/600',
      'https://picsum.photos/seed/lamp9b/600/600',
      'https://picsum.photos/seed/lamp9c/600/600',
    ],
    variants: { colors: ['White', 'Black', 'Gold'] },
    tags: ['lamp', 'lighting', 'charger', 'desk'],
  },
  {
    id: '10',
    name: 'Handwoven Boho Area Rug 5x8',
    price: 199.99,
    originalPrice: 279.99,
    category: 'home',
    rating: 4.4,
    reviews: 312,
    stock: 12,
    badge: 'Sale',
    description: 'Add warmth and texture to any room with this handwoven area rug. Made by artisans using traditional techniques, each rug is unique with subtle variations.',
    features: ['100% natural wool', 'Hand-knotted by artisans', 'Non-slip backing', 'Eco-friendly dyes', '5\' x 8\' dimensions', 'Spot clean or professional clean'],
    images: [
      'https://picsum.photos/seed/rug10a/600/600',
      'https://picsum.photos/seed/rug10b/600/600',
      'https://picsum.photos/seed/rug10c/600/600',
    ],
    variants: { colors: ['Terracotta/Cream', 'Indigo/Natural', 'Sage/Sand', 'Rust/Brown'] },
    tags: ['rug', 'home decor', 'handmade', 'boho'],
  },
  {
    id: '11',
    name: 'Ceramic Pour-Over Coffee Set',
    price: 64.99,
    originalPrice: null,
    category: 'home',
    rating: 4.8,
    reviews: 687,
    stock: 45,
    badge: null,
    description: 'Elevate your morning ritual with this handcrafted ceramic pour-over coffee set. Includes dripper, server, and two mugs. Microwave and dishwasher safe.',
    features: ['Handcrafted ceramic', 'Includes dripper + server + 2 mugs', 'Microwave safe', 'Dishwasher safe', 'Lead-free glaze', '12oz server capacity'],
    images: [
      'https://picsum.photos/seed/coffee11a/600/600',
      'https://picsum.photos/seed/coffee11b/600/600',
      'https://picsum.photos/seed/coffee11c/600/600',
    ],
    variants: { colors: ['Matte White', 'Speckled Gray', 'Terracotta', 'Sage Green'] },
    tags: ['coffee', 'ceramic', 'kitchen', 'pour-over'],
  },
  {
    id: '12',
    name: 'Velvet Accent Chair',
    price: 449.99,
    originalPrice: 599.99,
    category: 'home',
    rating: 4.6,
    reviews: 234,
    stock: 7,
    badge: 'Sale',
    description: 'Add a touch of luxury to your living space with this statement velvet accent chair. Features solid wood legs and high-density foam cushioning for supreme comfort.',
    features: ['Premium velvet upholstery', 'Solid walnut legs', 'High-density foam cushion', '360lb weight capacity', 'Easy assembly', 'Spot clean only'],
    images: [
      'https://picsum.photos/seed/chair12a/600/600',
      'https://picsum.photos/seed/chair12b/600/600',
      'https://picsum.photos/seed/chair12c/600/600',
    ],
    variants: { colors: ['Emerald Green', 'Dusty Rose', 'Cobalt Blue', 'Mustard Yellow', 'Charcoal'] },
    tags: ['chair', 'velvet', 'furniture', 'living room'],
  },
  // Sports
  {
    id: '13',
    name: 'Adjustable Dumbbell Set (5-50lbs)',
    price: 299.99,
    originalPrice: 379.99,
    category: 'sports',
    rating: 4.7,
    reviews: 1829,
    stock: 10,
    badge: 'Hot',
    description: 'Replace 15 sets of weights with one compact dumbbell set. Quick-change dial lets you adjust weight from 5 to 50lbs in 2.5lb increments. Perfect for home gyms.',
    features: ['5-50lbs adjustable', '2.5lb increments', 'Dial-select mechanism', 'Ergonomic handle', 'Storage tray included', 'Replaces 15 sets'],
    images: [
      'https://picsum.photos/seed/dumbbells13a/600/600',
      'https://picsum.photos/seed/dumbbells13b/600/600',
      'https://picsum.photos/seed/dumbbells13c/600/600',
    ],
    variants: { colors: ['Black/Red', 'Black/Gray'] },
    tags: ['dumbbells', 'weights', 'home gym', 'fitness'],
  },
  {
    id: '14',
    name: 'All-Terrain Trail Running Shoes',
    price: 139.99,
    originalPrice: null,
    category: 'sports',
    rating: 4.5,
    reviews: 967,
    stock: 24,
    badge: 'New',
    description: 'Tackle any terrain with confidence. These trail runners feature a Vibram outsole for maximum grip, responsive foam midsole, and a protective rock plate.',
    features: ['Vibram Megagrip outsole', 'Protective rock plate', 'Responsive foam midsole', 'Water-resistant upper', 'Drainage ports', 'Heel-to-toe drop: 6mm'],
    images: [
      'https://picsum.photos/seed/trailshoe14a/600/600',
      'https://picsum.photos/seed/trailshoe14b/600/600',
      'https://picsum.photos/seed/trailshoe14c/600/600',
    ],
    variants: {
      colors: ['Black/Orange', 'Blue/Yellow', 'Green/Gray', 'Red/Black'],
      sizes: ['7', '8', '9', '10', '11', '12', '13'],
    },
    tags: ['shoes', 'trail', 'running', 'outdoor'],
  },
  {
    id: '15',
    name: 'Premium Yoga Mat with Alignment Lines',
    price: 79.99,
    originalPrice: 99.99,
    category: 'sports',
    rating: 4.6,
    reviews: 2341,
    stock: 60,
    badge: 'Sale',
    description: 'Take your practice to the next level with this professional-grade yoga mat. Natural rubber base provides superior grip, while the microfiber top absorbs moisture.',
    features: ['Natural rubber base', 'Microfiber top layer', '6mm thickness', 'Alignment guide lines', 'Carrying strap included', 'Eco-friendly materials'],
    images: [
      'https://picsum.photos/seed/yogamat15a/600/600',
      'https://picsum.photos/seed/yogamat15b/600/600',
      'https://picsum.photos/seed/yogamat15c/600/600',
    ],
    variants: { colors: ['Celestial Blue', 'Mandala Purple', 'Desert Sand', 'Forest Green', 'Black'] },
    tags: ['yoga', 'mat', 'fitness', 'meditation'],
  },
  {
    id: '16',
    name: 'Smart Fitness Resistance Bands Set',
    price: 49.99,
    originalPrice: null,
    category: 'sports',
    rating: 4.3,
    reviews: 1124,
    stock: 75,
    badge: null,
    description: 'Take your resistance training anywhere with this complete set of 5 bands ranging from 10-50lbs. Compatible with our fitness app for guided workouts.',
    features: ['5 resistance levels (10-50lbs)', 'Snap-proof latex', 'Stackable up to 150lbs', 'Door anchor included', 'Carry bag', 'App-guided workouts'],
    images: [
      'https://picsum.photos/seed/bands16a/600/600',
      'https://picsum.photos/seed/bands16b/600/600',
      'https://picsum.photos/seed/bands16c/600/600',
    ],
    variants: { colors: ['Multicolor Set'] },
    tags: ['resistance bands', 'fitness', 'portable', 'strength'],
  },
  // Beauty
  {
    id: '17',
    name: 'Vitamin C Brightening Serum 30ml',
    price: 58.99,
    originalPrice: 74.99,
    category: 'beauty',
    rating: 4.7,
    reviews: 3892,
    stock: 48,
    badge: 'Sale',
    description: '20% stabilized Vitamin C serum formulated with ferulic acid and Vitamin E for enhanced efficacy. Brightens, firms, and protects against environmental damage.',
    features: ['20% L-Ascorbic Acid', 'Ferulic Acid + Vitamin E', 'Paraben-free', 'Fragrance-free', 'Dermatologist tested', 'Cruelty-free'],
    images: [
      'https://picsum.photos/seed/serum17a/600/600',
      'https://picsum.photos/seed/serum17b/600/600',
      'https://picsum.photos/seed/serum17c/600/600',
    ],
    variants: { colors: ['30ml', '60ml'] },
    tags: ['serum', 'vitamin c', 'brightening', 'skincare'],
  },
  {
    id: '18',
    name: 'Hydrating Lip Collection Set',
    price: 39.99,
    originalPrice: null,
    category: 'beauty',
    rating: 4.5,
    reviews: 1567,
    stock: 85,
    badge: 'New',
    description: 'A curated collection of 6 hydrating lip products including glosses, balms, and a satin lipstick. Infused with hyaluronic acid and vitamin E for long-lasting moisture.',
    features: ['6-piece collection', 'Hyaluronic acid enriched', 'Vitamin E complex', 'Long-lasting formula', 'Buildable coverage', 'Cruelty-free & vegan'],
    images: [
      'https://picsum.photos/seed/lipset18a/600/600',
      'https://picsum.photos/seed/lipset18b/600/600',
      'https://picsum.photos/seed/lipset18c/600/600',
    ],
    variants: { colors: ['Nude Collection', 'Berry Collection', 'Rose Collection'] },
    tags: ['lipstick', 'makeup', 'hydrating', 'gift set'],
  },
  {
    id: '19',
    name: 'Luxury Hair Care Trio',
    price: 89.99,
    originalPrice: 119.99,
    category: 'beauty',
    rating: 4.6,
    reviews: 2134,
    stock: 32,
    badge: 'Sale',
    description: 'Transform your hair with this salon-quality trio featuring a bond-strengthening shampoo, nourishing conditioner, and repairing hair mask infused with keratin and argan oil.',
    features: ['Keratin & Argan oil blend', 'Sulfate-free formula', 'Color-safe', 'Includes: shampoo + conditioner + mask', 'Salon quality', 'Vegan & cruelty-free'],
    images: [
      'https://picsum.photos/seed/haircare19a/600/600',
      'https://picsum.photos/seed/haircare19b/600/600',
      'https://picsum.photos/seed/haircare19c/600/600',
    ],
    variants: { colors: ['For Damaged Hair', 'For Curly Hair', 'For Color-Treated Hair'] },
    tags: ['hair', 'shampoo', 'conditioner', 'keratin'],
  },
  {
    id: '20',
    name: 'Rose Oud Eau de Parfum 50ml',
    price: 129.99,
    originalPrice: null,
    category: 'beauty',
    rating: 4.8,
    reviews: 876,
    stock: 20,
    badge: 'Hot',
    description: 'A sophisticated blend of Bulgarian rose, aged oud wood, and warm amber. This long-lasting fragrance opens with fresh citrus notes and settles into a rich, velvety base.',
    features: ['Top: Bergamot, Pink Pepper', 'Heart: Bulgarian Rose, Iris', 'Base: Oud, Amber, Musk', '50ml / 1.7 fl oz', '8-12hr longevity', 'Includes velvet pouch'],
    images: [
      'https://picsum.photos/seed/perfume20a/600/600',
      'https://picsum.photos/seed/perfume20b/600/600',
      'https://picsum.photos/seed/perfume20c/600/600',
    ],
    variants: { colors: ['50ml', '100ml'] },
    tags: ['perfume', 'fragrance', 'rose', 'oud'],
  },
]

export function getProductById(id) {
  return products.find((p) => p.id === id) || null
}

export function getProductsByCategory(category) {
  if (!category || category === 'all') return products
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(count = 8) {
  return products.filter((p) => p.badge).slice(0, count)
}

export function getRelatedProducts(product, count = 4) {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, count)
}

export function searchProducts(query) {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)) ||
      p.category.includes(q)
  )
}
